### Get a card
GET http://localhost:5000/api/cards/620e870a6dcc179b61bcbcec HTTP/1.1

### 
POST http://localhost:5000/api/cards HTTP/1.1
content-type: application/json

{
  "listId": "62151ba983bc943d669df11c",
  "card": {
    "title": "New and Improved",
  }
}

###
PUT http://localhost:5000/api/cards/620e870a6dcc179b61bcbcec HTTP/1.1
content-type: application/json

{
  "card": {
    "title": "Updated Title Again",
    "description": "This is our new and improved card Schema",
  }
}
