POST http://localhost:5000/api/boards HTTP/1.1
content-type: application/json

{
  "board": {
    "title": "Web dev"
  }
}

###
GET http://localhost:5000/api/boards HTTP/1.1

###
GET http://localhost:5000/api/boards/620e86d75c5d1d7dc0b1ca11 HTTP/1.1